#!/bin/bash
# **********************************************************************
# Ericsson Radio Systems AB                                     SCRIPT
# **********************************************************************
#
# (c) Ericsson Radio Systems AB 2016 - All rights reserved.
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Radio Systems AB, Sweden. The programs may be used and/or
# copied only with the written permission from Ericsson Radio Systems AB
# or in accordance with the terms and conditions stipulated in the
# agreement/contract under which the program(s) have been supplied.
#
# **********************************************************************
#   Command Section
#
# **********************************************************************
#
#   Main body of program
#
# ********************************************************************
#
IP=\$(ip -o -4 addr list eth0 | perl -n -e 'if (m{inet\\s([\\d\\.]+)\\/\\d+\\s}xms) { print \$1 }')
echo "CONTAINER_IP=\$IP"
export SPARK_LOCAL_IP=\$IP
export SPARK_PUBLIC_DNS=\$IP
# Avoid the default Docker behavior of mapping our IP address to an unreachable host name
umount /etc/hosts
spark-submit  --class com.ericsson.aia.bps.engine.service.BPSPipeLineExecuter /bps-engine-uber-0.0.1-SNAPSHOT.jar  /flow.xml  --properties-file /confi.properties
